Revert "Use jenkins to run ci"
This reverts commit ea607aee36ef5ea092b13dab84b6865d68c89738.

```
java.io.IOException: Failed to run image 'jhipster/jhipster:v5.8.2'. Error: docker: Error response from daemon: linux spec user: unable to find user jenkins: no matching entries in passwd file.
	at org.jenkinsci.plugins.docker.workflow.client.DockerClient.run(DockerClient.java:133)
```